ДЗ 9
dmitrii-subb/2022-2-VK-EDU-FS-Frontend-D-Oreshkin pull request #11
Opened 2022-12-02 21:00 UTC by dmitrii-subb

# Домашнее задание № 9

Прошу @martinkomitsky, @haseprogram или @vaganov-spb проверить его.

Что было сделано:
* перенес проект на redux

### Демонстрация работы

![redux](https://user-images.githubusercontent.com/71903279/205385105-1e8201a6-78da-4eb5-8469-d3d8920101ee.gif)

2022-12-04 11:17 UTC, martinkomitsky commented on react-chat/src/reducers/viewReduser.js
> +import { SET_MOBILE_VIEW, SET_DESKTOP_VIEW } from "../constants/ActionTypes";
потом можно когда-нибудь исправить на reducer)

2022-12-04 11:20 UTC, martinkomitsky commented on react-chat/src/reducers/activeChatReduser.js
> +import { SET_ACTIVE_CHAT } from "../constants/ActionTypes";
в целом, активный чат - это не та инфа, которую стоит размещать в сторе. Как я раньше предлагал, это достаточно хранить в урле. 
Т.е. `/chats/:id`. Например, `/chats/123`, либо `/chats/456`

2022-12-04 11:39 UTC, martinkomitsky commented on react-chat/src/actions/activeChatReduser.js
> +import { SET_ACTIVE_CHAT } from "../constants/ActionTypes";
вроде бы action, а написано reducer, хм

2022-12-08 15:41 UTC, martinkomitsky commented on react-chat/src/actions/activeChatReduser.js
> +};
Нужно переименовать всё на action, либо вообще удалить постфикс

2022-12-08 15:43 UTC, dmitrii-subb commented on react-chat/src/actions/activeChatReduser.js
> +};
работаю над этим

2022-12-08 15:46 UTC, martinkomitsky commented on react-chat/src/components/ChatBody/ChatBody.jsx
> +  }, []);
Есть уверенное ощущение, что тут надо делать отключение от канала и отписку. Иначе при каждом новом маунте этого компонента, будет подниматься новый вебсокет, происходить новая подписка.
Нормальным решением было бы вынести вебсокет на уровень выше и менеджить сторы там.

2022-12-08 15:46 UTC, martinkomitsky requested changes
См. комменты

2022-12-08 16:20 UTC, dmitrii-subb commented on react-chat/src/actions/activeChatReduser.js
> +};
готово

2022-12-08 16:20 UTC, dmitrii-subb commented on react-chat/src/components/ChatBody/ChatBody.jsx
> +  }, []);
перенес вебсокет в App.js

2022-12-08 16:21 UTC, dmitrii-subb commented on react-chat/src/actions/activeChatReduser.js
> +import { SET_ACTIVE_CHAT } from "../constants/ActionTypes";
переделал

2022-12-08 16:21 UTC, dmitrii-subb commented on react-chat/src/reducers/viewReduser.js
> +import { SET_MOBILE_VIEW, SET_DESKTOP_VIEW } from "../constants/ActionTypes";
исправил

2022-12-08 20:44 UTC, martinkomitsky commented on react-chat/src/reducers/messageReduser.js
> +import {
<img width="252" alt="image" src="https://user-images.githubusercontent.com/14847018/206563670-d8ed28f4-586d-4923-92f9-d1aa9e190d29.png">
все ещё `КрасныеЮзеры`. На фикс!

2022-12-08 20:48 UTC, martinkomitsky requested changes
Дочинить редусеров

2022-12-10 17:30 UTC, dmitrii-subb commented on react-chat/src/reducers/messageReduser.js
> +import {
больше никакик красных юзеров!

2022-12-10 18:15 UTC, martinkomitsky requested changes
<img width="414" alt="image" src="https://user-images.githubusercontent.com/14847018/206869517-7acb3620-3ce6-4955-9237-ac68818a8000.png">

2022-12-10 19:02 UTC, dmitrii-subb commented
> <img alt="image" width="414" src="https://user-images.githubusercontent.com/14847018/206869517-7acb3620-3ce6-4955-9237-ac68818a8000.png">

открыл для себя возможность искать и заменять текст по всему проету. теперь точно никаких redusers

2022-12-10 20:05 UTC, martinkomitsky approved these changes
12

2022-12-10 20:05 UTC, merged