Add files via upload
dmitrii-subb/2022-2-VK-EDU-FS-Frontend-D-Oreshkin pull request #12
Opened 2022-12-03 21:06 UTC by dmitrii-subb

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram или @vaganov-spb проверить его.

Что было сделано:
* Добавлена авторизация  через google

![login](https://user-images.githubusercontent.com/71903279/205462064-3d4e8142-d654-4cfe-b38c-4ef0a35b788e.gif)

2022-12-04 11:35 UTC, martinkomitsky commented
@dmitri01996 расскажи, пожалуйста, как ты пользуешься гитом?
<img width="380" alt="image" src="https://user-images.githubusercontent.com/14847018/205488141-f2cf71ca-a410-4e23-acf1-0e43c23a3811.png">

Волнуюсь.

2022-12-08 16:58 UTC, dmitrii-subb commented
> @dmitri01996 расскажи, пожалуйста, как ты пользуешься гитом? <img alt="image" width="380" src="https://user-images.githubusercontent.com/14847018/205488141-f2cf71ca-a410-4e23-acf1-0e43c23a3811.png">
> 
> Волнуюсь.

исправил замечания к прошлой домашке и залил правильным путем - через консоль

2022-12-10 20:06 UTC, martinkomitsky commented
> > @dmitri01996 расскажи, пожалуйста, как ты пользуешься гитом? <img alt="image" width="380" src="https://user-images.githubusercontent.com/14847018/205488141-f2cf71ca-a410-4e23-acf1-0e43c23a3811.png">
> > Волнуюсь.
> 
> исправил замечания к прошлой домашке и залил правильным путем - через консоль

тем не менее, предполагаемые конфликты случились

2022-12-10 20:06 UTC, martinkomitsky requested changes
отписал выше

2022-12-24 15:19 UTC, martinkomitsky commented
@dmitri01996 @dmitrii-subb всё еще нужен фикс(((

2022-12-30 15:03 UTC, martinkomitsky approved these changes
12

2022-12-30 15:03 UTC, merged