ДЗ 5
dmitrii-subb/2022-2-VK-EDU-FS-Frontend-D-Oreshkin pull request #6
Opened 2022-11-10 15:44 UTC by dmitrii-subb

# Домашнее задание № 5

Прошу @martinkomitsky, @haseprogram или @vaganov-spb проверить его.

Что было сделано:
* Приложенеие переписано на react.js
* Решил объединить страницу с чатами и страницу конкретного чата
* Деплоил приложение через npm пакет gh-pages
* Наконец разобрался с гитхабом :)

2022-11-11 19:11 UTC, martinkomitsky commented on .github/workflows/gh-pages.yml
> +        publish_dir: ./public
Нужно сделать так, потому что в исходниках ничего полезного нет
```suggestion
        publish_dir: ./react-chat/build
```

2022-11-11 19:32 UTC, martinkomitsky commented on react-chat/public/index.html
> +    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
Можно заменить на либу из условия дз

2022-11-11 19:37 UTC, martinkomitsky commented on react-chat/src/components/ChatMessageForm/ChatMessageForm.jsx
> +    let [value, setValue] = useState('message');
Немного раздражает) если это для тестов было, то лучше выпилить. Если хотелось сделать красивую заглушку при пустом поле с подсказкой, то это атрибут [placeholder](https://www.w3schools.com/tags/att_input_placeholder.asp)

2022-11-11 19:39 UTC, martinkomitsky commented on react-chat/src/pages/SidebarPage/SidebarPage.jsx
> +            {/* <FloatButton /> */}
а что стало с кнопкой? мб вернуть?

2022-11-11 19:40 UTC, martinkomitsky commented on react-chat/src/pages/ChatPage/ChatPage.jsx
> +}
Для удобства очень советую подобные функции выносить в отдельный файл

2022-11-11 19:40 UTC, martinkomitsky commented on react-chat/src/pages/ChatPage/ChatPage.jsx
> +  return true;
тоже можно вынести

2022-11-11 19:47 UTC, martinkomitsky commented on react-chat/src/pages/ChatPage/ChatPage.jsx
> +        //! срабатывает два раза
Не получилось воспроизвести, только один раз срабатывает

2022-11-11 19:48 UTC, martinkomitsky commented on react-chat/src/pages/ChatPage/ChatPage.jsx
> +    //! при первом клике рендерится 4 раза, затем по два - почему?
Тут норма, если происходит изменение состояния или пропс. Функциональные компоненты всегда выполняются, т.к. это считай функция render
Проверь еще раз сам, плз, а потом удали коммент, если все ок)

2022-11-11 19:58 UTC, martinkomitsky requested changes
Нужно исправить комменты и погнали)

2022-11-12 07:58 UTC, dmitrii-subb commented on react-chat/src/components/ChatMessageForm/ChatMessageForm.jsx
> +    let [value, setValue] = useState('message');
исправил

2022-11-12 07:58 UTC, dmitrii-subb commented on react-chat/src/pages/SidebarPage/SidebarPage.jsx
> +            {/* <FloatButton /> */}
вернул

2022-11-12 07:59 UTC, dmitrii-subb commented on react-chat/src/pages/ChatPage/ChatPage.jsx
> +}
вынес

2022-11-12 07:59 UTC, dmitrii-subb commented on react-chat/src/pages/ChatPage/ChatPage.jsx
> +  return true;
вынес, действительно удобно стало

2022-11-12 09:26 UTC, martinkomitsky approved these changes
12

2022-11-12 09:26 UTC, merged