ДЗ 6
dmitrii-subb/2022-2-VK-EDU-FS-Frontend-D-Oreshkin pull request #7
Opened 2022-11-13 07:42 UTC by dmitrii-subb

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram или @vaganov-spb проверить его.

Что было сделано:
* добавлен роутинг
* добавлена странца профиля (по нажатию бургер кнопки будет переход на страницу профиля)

2022-11-13 19:25 UTC, martinkomitsky requested changes
Пожалуйста, следи за валидностью PR. Найди ошибку сам)

2022-11-14 11:32 UTC, dmitrii-subb commented
убрал конфликты

2022-11-15 17:58 UTC, martinkomitsky commented on react-chat/src/App.js
> +  let [chatId, setChatId] = useState(0);
стейты всегда конст, так как не меняются напрямую

2022-11-15 17:58 UTC, martinkomitsky commented on react-chat/src/App.js
> +          <Route index element={<SidebarPage openChat={openChat}/>} />
Рекомендую в будущем сделать при переходе на конкретный чат тоже смену урла (ну типа /#/chats/5)

2022-11-15 18:01 UTC, merged